import { Unidad } from "../enum/Unidad";
import { Agroquimico } from "./Agroquimico";
import { Proveedor } from "./Proveedor";

export interface Producto {
  id?: string; // Optional, generated by backend
  name: string;
  unit: Unidad; // Backend expects "KG", "L", etc.
  amount: number; // BigDecimal mapped to number
  brand: string;
  createdAt: string; // ZonedDateTime serialized as ISO string
  agrochemicalId: string;
  agrochemical: Agroquimico;
  providers?: Proveedor[]; // Optional
}
